### ISSUE TITLE
[Bug]_Maya Picky about import order of the resolver

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-usd-resolver#26]
### Describe the bug

This will fail with an error:
```python
from pxr import Ar
import time
from usdAssetResolver import AyonUsdResolver

Ar.SetPreferredResolver("AyonUsdResolver")
resolver = Ar.GetResolver()
context = AyonUsdResolver.ResolverContext()
```

Stack trace:
```
# Error: DLL load failed while importing _ayonUsdResolver: The specified module could not be found.
# # Traceback (most recent call last):
# #   File "<maya console>", line 5, in <module>
# #   File "E:\dev\ayon-usd\client\ayon_usd\downloads\Maya2024_2_Py310_Win_Windows_AMD64\ayonUsdResolver\lib\python\usdAssetResolver\AyonUsdResolver\__init__.py", line 2, in <module>
# #     Tf.PreparePythonModule()
# #   File "C:\Program Files\Autodesk\MayaUSD\Maya2024\0.27.0_202402071410-bf4bd3e\mayausd\USD\lib\python\pxr\Tf\__init__.py", line 88, in PreparePythonModule
# #     module = importlib.import_module(
# #   File "C:\Program Files\Autodesk\Maya2024\Python\lib\importlib\__init__.py", line 126, in import_module
# #     return _bootstrap._gcd_import(name[level:], package, level)
# # ImportError: DLL load failed while importing _ayonUsdResolver: The specified module could not be found.
```
It fails on line: `from usdAssetResolver import AyonUsdResolver`

**However**, if you load the `mayaUsd` plug-in and create an empty stage (mayaUsdProxyShape). Then these imports work fine.

---

#### Workaround ✅ 

However **this code does work**, without having `mayaUsd` plug-in loaded nor a stage opened.
```python
from pxr import Ar
import time

Ar.SetPreferredResolver("AyonUsdResolver")
resolver = Ar.GetResolver()

from usdAssetResolver import AyonUsdResolver
context = AyonUsdResolver.ResolverContext()
```

### Describe yourself

TD

### To Reproduce

1. Launch Maya with resolver.
2. Run:

```python
from pxr import Ar
import time
from usdAssetResolver import AyonUsdResolver

Ar.SetPreferredResolver("AyonUsdResolver")
resolver = Ar.GetResolver()
context = AyonUsdResolver.ResolverContext()
```

### How did you discover the bug?

I ran that code when testing resolver.

### Expected behaviour

Preferably, we can make AYON USD Resolver in Maya less picky about the import order.

Looking at the provided "workaround" I wonder if there's anything we _should_ do to enforce the default resolver since that seemed to fix the import?

### Hardware Setup

n/a

### Software Setup

Maya 2024.2

### User Type

TD

### What platform are you running on?

Windows 10

### Is there an existing issue with this?

- [X] I have searched the existing issues

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
This is still the case in Maya 2026 recently. Might be worth to see if we can do anything in this area. It's low priority though.

**Comment by tadeas-hejnic** [comment]
I tested it again and the issue is present just on windows, but currently it is connected to the functionality of the whole resolver. Everything works as expected if [this line](https://github.com/ynput/ayon-usd-resolver/blob/571cda9174641290bf61450f7a1d976b3a0bd225/src/AyonUsdResolver/plugInfo.json.in#L9) is there. 

Without the line it works on Linux (both Maya and Houdini), but on Windows works only Houdini and Maya works just with the 

`"uriSchemes": ["ayon", "ayon+entity"]` in `plugInfo.json`.

My assumption is that Maya resolve the `AdskAssetResolver` and `AyonUsdResolver` as interchangeable and loads only the default AdskAssetResolver. I found a working solution - add `Ar.SetPreferredResolver("AyonUsdResolver")` into [userSetup.py](https://github.com/ynput/ayon-maya/blob/develop/client/ayon_maya/startup/userSetup.py) and the resolver (current develop build) is loaded correctly and working as expected.

Potentially it could fix also this issue which is also on linux: https://github.com/Autodesk/maya-usd/issues/4537. But I didn't test it so I'm not sure about it.

**Comment by BigRoy** [comment]
> I found a working solution - add `Ar.SetPreferredResolver("AyonUsdResolver")` into [userSetup.py](https://github.com/ynput/ayon-maya/blob/develop/client/ayon_maya/startup/userSetup.py) and the resolver (current develop build) is loaded correctly and working as expected.

If that's the case, let's add a prelaunch hook that does this in `ayon-usd` for maya if the resolver is enabled and we're launching maya host.
